name: jhd1313m1-lcd-upm-javascript-joule-example
version: '1.0' 
summary: Lcd javascript upm example for Intel Joule
description: |
  Lcd javascript example from UPM lib for Intel Joule

grade: stable 
confinement: strict

apps:
 run:
   command: nodejs $SNAP/jhd1313m1-lcd.js

parts:
  move:
    plugin: dump
    source: .
    stage-packages:
       - nodejs-dev
       - node-upm
       - node-mraa
       - node-commander
       - mraa-imraa
