name: grove-linefinder-upm-java-joule-example
version: '1.0' 
summary: A java upm with maven example
description: |
  A java example from upm lib, builded with maven, using grove-linefinder sensor.

grade: stable 
confinement: strict

apps:
 run:
   command: java -classpath $SNAP/jar/grove-linefinder-1.0.jar:$SNAP/usr/share/java/upm_grovelinefinder.jar GroveLineFinderSample

parts:
  local:
    plugin: maven
    stage-packages:
       - libupm-java
       - mraa-imraa
