name: jhd1313m1-lcd-upm-python-joule-example
version: '1.0' 
summary: A python upm example
description: |
  A python example from UPM lib.

grade: stable 
confinement: strict

apps:
 run:
   command: python $SNAP/jhd1313m1-lcd.py

parts:
  local: 
    plugin: nil
    stage-packages: 
       - python-upm
       - python-mraa
       - python
       - mraa-imraa
  movefiles:
    plugin: dump
    source: .
