name: grove-speaker-upm-java-joule-example
version: '1.0' 
summary: A java upm with maven example
description: |
  A java example from upm lib, builded with maven, using grove-speaker sensor.

grade: stable 
confinement: strict

apps:
 run:
   command: java -classpath $SNAP/jar/grove-speaker-1.0.jar:$SNAP/usr/share/java/upm_grovespeaker.jar GroveSpeakerSample

parts:
  local:
    plugin: maven
    stage-packages:
       - libupm-java
       - mraa-imraa
