name: grove-speaker-cpp-joule-example
version: '1.0' 
summary: Grove speaker upm example for snapcraft
description: |
  Grove speaker example from UPM lib for Intel Joule

grade: stable
confinement: strict

apps:
  run:
    command: bin/speaker
    
parts:
  grovespeaker:
    plugin: cmake
    stage-packages:
      - libupm-dev 
      - libmraa-dev
