name: blink-mraa-javascript-joule-example
version: '1.0' 
summary: A mraa javascript example
description: |
  A javascript example from MRAA lib.

grade: stable 
confinement: strict

apps:
 run:
   command: nodejs $SNAP/Blink-IO.js

parts:
  move:
    plugin: dump
    source: .
    stage-packages:
       - nodejs-dev
       - node-mraa
       - node-commander
       - mraa-imraa
