name: grove-linefinder-cpp-example
version: '1.0' 
summary: Grove linefinder upm example for snapcraft
description: |
  Grove linefinder example from UPM lib

grade: stable
confinement: strict

apps:
  run:
    command: bin/linefinder
    
parts:
  grovespeaker:
    plugin: cmake
    stage-packages:
      - libupm-dev 
      - libmraa-dev
