name: blink-mraa-python-joule-example
version: '1.0' 
summary: A mraa python example
description: |
  A python example from MRAA lib.

grade: stable 
confinement: strict

apps:
 run:
   command: bin/wrapper

parts:
  local: 
    plugin: dump
    organize:
      'wrapper' : bin/
      '*.py' : bin/
    stage-packages: 
       - python3-mraa
       - python3
