name: blink-mraa-python-example
version: '1.0' 
summary: A mraa python example
description: |
  A python example from MRAA lib.

grade: stable 
confinement: strict

apps:
 run:
   command: python $SNAP/blink.py

parts:
  local: 
    plugin: nil
    stage-packages: 
       - python-mraa
       - python
       - mraa-imraa
  movefiles:
    plugin: dump
    source: .