name: grove-speaker-upm-python-example
version: '1.0' 
summary: A python upm example
description: |
  A python example from UPM lib with grove-speaker sensor.

grade: stable 
confinement: strict

apps:
 run:
   command: python $SNAP/grovespeaker.py

parts:
  local: 
    plugin: nil
    stage-packages: 
       - python-upm
       - python-mraa
       - python
       - mraa-imraa
  movefiles:
    plugin: dump
    source: .
