name: grove-linefinder-upm-python-joule-example
version: '1.0' 
summary: A python upm example
description: |
  A python example from UPM lib with grove-linefinder sensor.

grade: stable 
confinement: strict

apps:
  run:
   command: python $SNAP/grovelinefinder.py

parts:
  local: 
    plugin: nil
    stage-packages: 
       - python-upm
       - python
       - mraa-imraa
  movefiles:
    plugin: dump
    source: .