name: blink-mraa-java-joule-example
version: '1.0' 
summary: A mraa java example
description: |
  A java example from MRAA lib, builded with maven.

grade: stable 
confinement: strict

apps:
 run:
   command: bin/wrapper

parts:
  local:
    plugin: maven
    stage-packages:
       - libmraa-java  
  wrapper: 
    plugin: make
    source: .
