name: blink-mraa-java-joule-example
version: '1.0' 
summary: A mraa java example
description: |
  A java example from MRAA lib, builded with maven.

grade: stable 
confinement: strict

apps:
 run:
   command: java -classpath $SNAP/jar/blink-led-1.0.jar:$SNAP/usr/share/java/mraa.jar BlinkIO

parts:
  local:
    plugin: maven
    stage-packages:
       - libmraa-java
       - mraa-imraa  
