name: blink-mraa-cpp-example
version: '1.0' 
summary: mraa for snapcraft
description: |
  Blink Example from MRAA lib

grade: stable 
confinement: strict 

apps:
  run:
    command: bin/blink    
    
parts:
  blink:
    plugin: cmake
    stage-packages:
      - libmraa1 
      - libmraa-dev
      - mraa-imraa
